prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

grafana:
  adminPassword: admin
  dashboards:
    default:
      node-exporter-dashboard:
        gnetId: 1860
        revision: 23
        datasource: Prometheus