apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: web
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - name: web-port-1
          containerPort: 80
      envFrom:
        - configMapRef:
            name: user-config

        - secretRef:
            name: user-secret

      volumeMounts:
        - mountPath: "/data"
          name: pv-test

  volumes:
    - name: pv-test
      persistentVolumeClaim:
        claimName: pvtest-claim