apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvtest-2gb
  labels:
    app: webserver
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  capacity:
    storage: 2Gi

  hostPath:
    path: /Users/ramaraja/workspace/Trainings/DevOps/k8s-examples 
