apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvtest-claim
  labels:
    app: webserver
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "example-nfs"
  resources:
    requests:
      storage: 2Gi