- name: Use tags in tasks
  hosts: local
  become: yes
  tasks:
    - name: Install curl
      ansible.builtin.package:
        name: curl
        state: present
      tags: install

    - name: Create demo file
      ansible.builtin.file:
        path: /tmp/demo_tag.txt
        state: touch
      tags: files